#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_open_world_terrain = env_modules.Clone()

env_open_world_terrain.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_open_world_terrain.add_source_files(env.modules_sources, "editor/*.cpp")
